services:

    logger-service:
        build:
            context: sustainability/services/logger-service
            dockerfile: Dockerfile
        ports:
            - "50000:3001"
        volumes:
            - ./services/logger-service/logs:/app/logs  
        networks:
            - sustain-network
            

    #Nasra's service - make sure your dockerfile is in a subfolder called food-upload-service
    food-upload-service:
       build:
           context: ./services/food-upload-service
           dockerfile: Dockerfile
       ports:
           - "3004:3004"
       networks:
           - sustain-network

    #Grace's service - make sure your dockerfile is in a subfolder called authentication-service
   
    authentication-service:
        build:
           context: ./services/authentication-service
           dockerfile: Dockerfile
        ports:
           - "3003:3003"
        networks:
           - sustain-network
            
    ## Limbani's service
    food-db-service:
        build:
            context: ./services/food-db-service
            dockerfile: Dockerfile
        ports:
            - "27017:27017"
        volumes:
            - food-db-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        networks:
            - sustain-network

networks:
    sustain-network:
        driver: bridge

volumes:
    food-db-data:
    logger-logs:



